apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  name: jeff-tan-pipeline-from-scratch-pipeline
spec:
  workspaces:
    - name: shared-workspace
      description: |
        This workspace stores the cloned repo and is available to all steps
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/upslopeio/lint-markdown-files
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: md-lint-run
      taskRef:
        name: markdown-lint
      runAfter:
        - clone-repository
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
      params:
        - name: args
          value: ["."]
